### ISSUE TITLE
A few bugs: drop views, mature games, polls & memory full

### ISSUE THREAD

**Issue by thearchitect2004** [jlplenio/crude-twitch-viewer-bot#200]
Hello,

After a few weeks of use, here are a few problems with the different versions of your software, for which I would like to thank you.

1) _CTVBot version KoFi 0.7.0_

- Impossible to go beyond 10 bots, most views don't count. 

I no longer use it.

2) _CTVBot version KoFi 0.6.0 v2 and the other version Ko-Fi_

- Polls / predictions / shoutouts / subgifts cause 100% CPU usage. If they are not closed quickly, the Blue Bots (connected) crash. 

3) _CTVBot Version 0.6.0 (not yet tested 0.6.1) AND both Ko-Fi versions_

- When playing Mature games, most views stop counting. If you restart the program (after restarting the computer because of the memory leak, see below), the views simply don't count any more, even though Crude displayed them in green or blue (for Ko-Fi). 

- If you change from a normal game to a mature game during a stream, you need to restart the program because all the views turn yellow and won't be counted. 

- At regular intervals (after two hours of streaming), under unknown conditions, when RAM reaches 95%, the CPU may fall to 1% usage. All the bots stay green but stop working, the view count drops. The program needs to be restarted. 

Used between 20 and 40 bots. 

**Please answer the following questions:**
- Windows 11
- Twitch
- Webshare Proxy Premium, yes

Nevertheless, apart from the problem of full RAM, the software generally works well. Thanks. I support you.

**Comment by jlplenio** [comment]
Hey @thearchitect2004. Wonderful collection of valuable information. I will respond in detail soon.

**Comment by jlplenio** [comment]
>CTVBot version KoFi 0.7.0_
>Impossible to go beyond 10 bots, most views don't count.

I tested it myself and with the old and new 0.7.1. version I released yesterday https://github.com/jlplenio/crude-twitch-viewer-bot/discussions/209, I was able to go to and test with 50 instances, albeit only with 3 auth_tokens! I have other supporters on ko-fi who state running 150+ instances stable.

>Polls / predictions / shoutouts / subgifts cause 100% CPU usage. If they are not closed quickly, the Blue Bots (connected) 

This is something I have not tested yet as I don't really use the tool myself or Twitch in general :)
I will have to keep an eye out for it and maybe spend some sub gifts 💸 


>When playing Mature games, most views stop counting. If you restart the program (after restarting the computer because of the memory leak, see below), the views simply don't count any more, even though Crude displayed them in green or blue (for Ko-Fi).

I had no problems with mature stream when testing. 

>If you change from a normal game to a mature game during a stream, you need to restart the program because all the views turn yellow and won't be counted.

This again, I have not tested. I would have to set up my own stream to monitored the behavior of Twitch when switching between normal and mature games.

>At regular intervals (after two hours of streaming), under unknown conditions, when RAM reaches 95%, the CPU may fall to 1% usage. All the bots stay green but stop working, the view count drops. The program needs to be restarted.

The maximum duration I tested was ~2h with no difficulties. But yes, because of this crude method, RAM, and overall system stability can quickly become an issue.


I will try to extend my testing with the remaining points.
