### ISSUE TITLE
Vps?

### ISSUE THREAD

**Issue by ForClosed** [jlplenio/crude-twitch-viewer-bot#32]
Anyway to use this on a hosting site to prevent bandwidth failure? For example Digital Ocean?

**Comment by jlplenio** [comment]
Excellent idea @ForClosed.
Since I was planning to write a detailed tutorial on this topic, I recently looked into vultr.com.
They offer a simple and quick setup for a Windows VPS needed to run CTVB. For example, the Cloud Compute Regular Intel Performance Windows Server with 6 cores and 16 GB memory, which was able to run ~40 instances for $ 0.244 / hour ($ 164 / month). The catch is that they charge by the hour, even when the VPS is down. So after setting up and using the VPS, you would have to destroy it and repeat all the steps the next time. Backups or snapshots are not a solution either, as it takes almost an hour to restore them. I can't recommend this solution with a clear conscience. Digital ocean works the same, I guess. Only venture down that path if you are aware of the finical risk (100$+ per month).

**Comment by ForClosed** [comment]
Hmm, I will do some research on hosting sites. Maybe around 20 instances could cut down the cost if its possible to find it cheaper. 
And by setup have you looked into programs like [putty](https://www.putty.org/) and [FileZilla](https://filezilla-project.org/) to make the bot compatible with the vps?

**Comment by jlplenio** [comment]
Setup is rather straight-forward because it is a Windows machine you control visually just like with VNC or TeamViewer. 
As stated above, the hourly price would be acceptable, but the VPS sites I tested bill you even if your VPS is offline. 
Because of the cost dangers, I discarded the idea of writing a tutorial.
