### ISSUE TITLE
Ideal Specs? - Can close if wrong place to ask

### ISSUE THREAD

**Issue by Mrbigchest** [jlplenio/crude-twitch-viewer-bot#34]
Having issues with an 3.2Ghz processor / 32 GB Ram. At around 20 instances my CPU is topped out (ram has plenty more room). Is this normal or do I need a significant upgrade to my processor for more? Has anyone tried using computing power through something like AWS? Is this feasible or more cost efficient? Thanks!

**Comment by Mrbigchest** [comment]
I don't believe AWS is a more viable solution, I think having a dedicated unit is the way to go. That said, are two 3.2ghz towers better than 1 3.9+ ghz tower? I'm targeting 100 instances if possible. Thanks!

**Comment by ForClosed** [comment]
I think the owner is working on something along the lines of making the bot work with a hosting platform, but judging by the costs everyone agrees that the price outweighs the payout of having an extra few instances. [Here](https://github.com/jlplenio/crude-twitch-viewer-bot/issues/32). From my opinion having two separate PCs would require you to have some sort of S tier type internet with ether cables. 

My internet is decent and I'm able to run about 10 instances before the stream starts losing bitrate. I also don't use the pc for playing games and instead use an elgato, so my pc is only running the instances and obs then nothing else. If you dont plan on streaming while running the bots I think that having another dedicated device would be great **if your internet could handle it**, because 100 instances would be very heavy. 

If not I am waiting for the owners final decision on if a personal server would be worth the cost.

**Comment by Mrbigchest** [comment]
Anyone know if graphics card quality has an impact on the number of instances able to be launched and sustained? Thanks!

**Comment by jlplenio** [comment]
The quality options a channel offers are most important. Any PC will quickly struggle, if only 1080p60 is available, for example. In contrast, many instances of 160p should be fairly easy. If you slowly increase your instances you should notice what bottlenecks first (cpu, ram, gpu, bandwidth). As I mentioned in #32, VPS solutions are not recommendable in my eyes.
