### ISSUE TITLE
live viewers 1

### ISSUE THREAD

**Issue by Lucifer192192** [jlplenio/crude-twitch-viewer-bot#43]
I noticed that Live Viewer was not added
live viewers 1
It's always 1
Can't seem to increase Live numbers?

**Comment by jlplenio** [comment]
You are talking about the live viewer count on twitch, correct?
If the viewer count is not increasing, it is likely because of:

- A. You do not use proxies or the proxies you use do not work with twitch.
An affordable source for working proxies can be found in the [Webshare Proxies Guide](https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Webshare.io-Proxies-Guide)

- B. The viewers of the CTVB tool are not reaching the livestream.

What does the _Proxies Available_ counter say (A.), and what colors do you have on the state indicator lights (B.):
https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Detailed-Tutorial#4-spawn-viewers

**Comment by yusufmahoni** [comment]
Tried so many proxies, but now one works. Do you have one availabe proxy for me to test it?
