### ISSUE TITLE
About the newly uploaded 0.4.0 version

### ISSUE THREAD

**Issue by MRSSSMR** [jlplenio/crude-twitch-viewer-bot#87]
Hi. I have a question.

I upgraded to 0.4.0 version and I think it's not stable.
For example, if the 0.3.1 version reliably recognized 100 people,
In version 0.4.0, only 95 out of 100 people are recognized.
(Surge in the number of people perceived as yellow)

Can I ask you to check?

**Comment by jlplenio** [comment]
Hmmmm. In the new version, the status of the instances is updated almost instantaneously. . So, the readings should even be more accurate than before. One possibility is, that the issue is caused by the new restart implementation. Restarts occur 20 min after the first instance starts. After 20 min, the oldest instance gets a restart every 1200s/instance_count. In your example, that would be 1200s/100 instances = 12s/instance. Each 12 s the oldest instance is restarted. So after 20 minutes it would be quite normal to see some instance status boxes to go to yellow because they are restarting. When I tested it, it was like a small yellow snake moving through the green instances. Mind you, when an instance restarts, it often counts twice on Twitch, making the actual viewer count on Twitch go even higher.

Maybe that could be the cause? You could test to disable restarts.
Again, restarts only happen 20 min after your first instance starts.

You can also search the logs for the string RESTARTING to see which instance restarted and which actually fell back to BUFFERING due to an error.

In the future, I might add a new status box color that indicates a restart.

Kudos for making it work with 100 instances 👍.

**Comment by trev361** [comment]
To piggyback off this question, is there a limit to the amount of proxies/instances the program can run?

**Comment by jlplenio** [comment]
> To piggyback off this question, is there a limit to the amount of proxies/instances the program can run?

No. The only limitation is the number of private proxies you buy and how strong your system is, especially the RAM.

**Comment by trev361** [comment]
Thank you. I was able to get it up to 128 but it was taking a huge toll on the system. Would a Linux version be less resource intensive or is it a matter of the multiple instances of Chrome running? I'd love to not run this on my PC but at a cloud service. The Windows licensing is expensive though.

**Comment by jlplenio** [comment]
You can try the experimental Unix version. It is not pretty, but it works. However, you need a desktop environment.
I have tested it on Ubuntu Desktop. I don't think it will be less resource intensive, maybe slightly.
https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/v0.4.0.unix

Every chrome instance is very resource hungry - perhaps I could go for two "tabs" per browser instance in the future.
But hey, 100 viewers are wonderful and should be sufficient.
